name: build

on: [push, pull_request]

jobs:
  run-test:
    runs-on: macOS-latest
    timeout-minutes: 10
    strategy:
      matrix:
        destination: [
          'macOS', 
          'iOS Simulator,name=iPhone 14', 
          'tvOS Simulator,name=Apple TV', 
          'watchOS Simulator,name=Apple Watch Series 8 (41mm)'
        ]
        swift-version: [5.0, 4.2, 4.0]
    steps:
      - uses: actions/checkout@v1
      - name: Debug build
        run: swift build
      - name: Execute test
        env:
          SWIFT_VERSION: ${{ matrix.swift-version }}
        run:  swift test
